trigger:
- release/rocm-rel-6.0


pool: NV31

steps:
- script: |
    
    echo "rocm" | sudo -S apt-get -y --allow-unauthenticated install build-essential libgtk2.0-dev libavcodec-dev libavformat-dev libswscale-dev python3-dev python3-numpy
    echo "rocm" | sudo -S apt-get -y --allow-unauthenticated install libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-dev unzip wget
    echo "rocm" | sudo -S apt-get -y install libopencv-dev python3-opencv
  displayName: 'Installing OpenCV'

- script: |
    echo "rocm" | sudo -S apt-get -y install nasm
    echo "rocm" | sudo -S apt-get -y install wget
    git clone -b 2.0.6.1 https://github.com/rrawther/libjpeg-turbo.git
    cd libjpeg-turbo
    mkdir build
    cd build
    cmake -DCMAKE_INSTALL_PREFIX=/usr \
          -DCMAKE_BUILD_TYPE=RELEASE  \
          -DENABLE_STATIC=FALSE       \
          -DCMAKE_INSTALL_DOCDIR=/usr/share/doc/libjpeg-turbo-2.0.3 \
          -DCMAKE_INSTALL_DEFAULT_LIBDIR=lib ..
    make -j$nproc
    echo "rocm" | sudo -S make install

  displayName: 'Installing TurboJpeg'

- script: |
    echo "rocm" | sudo -S apt-get -y update
    echo "rocm" | sudo -S apt-get -y install libsndfile1-dev
  displayName: 'Installing Libsndfile'

- script: |
    echo "rocm" | sudo -S apt-get -y install imagemagick
  displayName: 'Installing Imagemagick'

- script: |
    git clone https://github.com/NIFTI-Imaging/nifti_clib.git
    cd nifti_clib
    mkdir build
    cd build
    cmake ..
    echo "rocm" | sudo -S make -j4 install
  displayName: 'Installing Nifti-Imaging nifti_clib'

- script: |
    pip install openpyxl
  displayName: 'Pip installing openpyxl'

- script: |
    pwd
    mkdir build-hip
    cd build-hip
    cmake ..
    make -j8
    pwd
    echo "rocm" | sudo -S make install
  displayName: 'Building...'

- script: |
    cd build-hip
    make test
  displayName: 'Running tests'
