schedules:
- cron: '6 0 * * *'
  displayName: nightly build
  branches:
    include:
    - main

trigger: none

jobs:
  - job:
    variables:
    - group: common
    - template: /.azuredevops/variables-global.yml

    pool: HighEnd
    workspace:
      clean: all
    steps:
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-download.yml
      parameters:
        componentName: rocm-cmake
        branchName: develop
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-download.yml
      parameters:
        componentName: rocm-core
        branchName: master
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-download.yml
      parameters:
        componentName: ROCT-Thunk-Interface
        branchName: master
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-download.yml
      parameters:
        componentName: llvm-project
        branchName: amd-staging
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-download.yml
      parameters:
        componentName: ROCR-Runtime
        branchName: master
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-download.yml
      parameters:
        componentName: rocprofiler-register
        branchName: amd-mainline
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-download.yml
      parameters:
        componentName: clr
        branchName: rocm-6.0.x
    - script: 'ls -1R $(Agent.BuildDirectory)/rocm'
      displayName: 'Artifact listing'
    # upload everything bundled together
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-prepare-package.yml
      parameters:
        sourceDir: $(Agent.BuildDirectory)/rocm
    - template:  ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml
      parameters:
        publish: false
    # upload partial amdgpu compiler components
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-prepare-package.yml
      parameters:
        sourceDir: $(Agent.BuildDirectory)/rocm
        contentsString: |
          $(Agent.BuildDirectory)/rocm/amdgcn/*
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-prepare-package.yml
      parameters:
        sourceDir: $(Agent.BuildDirectory)/rocm/llvm
        clean: false
        contentsString: |
          $(Agent.BuildDirectory)/rocm/llvm/**/*
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml
      parameters:
        publish: false
    # upload amdgpu runtime
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-prepare-package.yml
      parameters:
        sourceDir: $(Agent.BuildDirectory)/rocm
        contentsString: |
          $(Agent.BuildDirectory)/rocm/lib/*.so
          $(Agent.BuildDirectory)/rocm/lib/*.so.*
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml
      parameters:
        publish: false
    # upload amdgpu runtime dev
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-prepare-package.yml
      parameters:
        sourceDir: '$(Agent.BuildDirectory)/rocm'
        contentsString: |
          $(Agent.BuildDirectory)/rocm/include/*
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml
