schedules:
- cron: '6 0 * * *'
  displayName: nightly build
  branches:
    include:
    - main

trigger: none

pool: gfx1100

steps:
# download tasks has built in 4x retry download count
# these will download last passing build for that branch
- task: DownloadBuildArtifacts@1
  displayName: Download latest rocm-cmake
  inputs:
    buildType: 'specific'
    project: ROCmPOCm
    pipeline: rocm-cmake
    specificBuildWithTriggering: true
    branchName: develop
    extractTars: true
- task: DownloadBuildArtifacts@1
  displayName: Download latest rocm-core
  inputs:
    buildType: 'specific'
    project: ROCmPOCm
    pipeline: rocm-core
    specificBuildWithTriggering: true
    branchName: master
    extractTars: true
- task: DownloadBuildArtifacts@1
  displayName: Download latest ROCT-Thunk-Interface
  inputs:
    buildType: 'specific'
    project: ROCmPOCm
    pipeline: ROCT-Thunk-Interface
    specificBuildWithTriggering: true
    branchName: master
    extractTars: true
- task: DownloadBuildArtifacts@1
  displayName: Download latest llvm-project
  inputs:
    buildType: 'specific'
    project: ROCmPOCm
    pipeline: llvm-project
    specificBuildWithTriggering: true
    branchName: amd-staging
    extractTars: true
- task: DownloadBuildArtifacts@1
  displayName: Download latest ROCR-Runtime
  inputs:
    buildType: 'specific'
    project: ROCmPOCm
    pipeline: ROCR-Runtime
    specificBuildWithTriggering: true
    branchName: master
    extractTars: true
- task: DownloadBuildArtifacts@1
  displayName: Download latest HIP
  inputs:
    buildType: 'specific'
    project: ROCmPOCm
    pipeline: clr
    specificBuildWithTriggering: true
    branchName: rocm-6.0.x
    extractTars: true
- script: 'ls -1R $(System.ArtifactsDirectory)'
  displayName: 'Artifact listing'
- task: CopyFiles@2
  displayName: 'Prepare for packaging'
  inputs:
    SourceFolder: $(System.ArtifactsDirectory)/extracted_tars/drop
    TargetFolder: $(Build.ArtifactStagingDirectory)
    retryCount: 3
- template: /templates/steps/publish.yml
