schedules:
- cron: '6 0 * * *'
  displayName: nightly build
  branches:
    include:
    - main

trigger: none

pool: gfx1100

steps:
- template: /templates/steps/artifact-download.yml
  parameters:
    componentName: rocm-cmake
    branchName: develop
- template: /templates/steps/artifact-download.yml
  parameters:
    componentName: rocm-core
    branchName: master
- template: /templates/steps/artifact-download.yml
  parameters:
    componentName: ROCT-Thunk-Interface
    branchName: master
- template: /templates/steps/artifact-download.yml
  parameters:
    componentName: llvm-project
    branchName: amd-staging
- template: /templates/steps/artifact-download.yml
  parameters:
    componentName: ROCR-Runtime
    branchName: master
- template: /templates/steps/artifact-download.yml
  parameters:
    componentName: clr
    branchName: rocm-6.0.x
- script: 'ls -1R $(Agent.BuildDirectory)/rocm'
  displayName: 'Artifact listing'
- task: CopyFiles@2
  displayName: 'Prepare for packaging'
  inputs:
    SourceFolder: $(Agent.BuildDirectory)/rocm
    TargetFolder: $(Build.BinariesDirectory)
    retryCount: 3
- template: /templates/steps/artifact-upload.yml
