resources:
  pipelines:
  - pipeline: llvm-project
    source: llvm-project
    branch: amd-staging
  - pipeline: ROCT-Thunk-Interface
    source: ROCT-Thunk-Interface
    branch: master

schedules:
- cron: '6 0 * * *'
  displayName: nightly build
  branches:
    include:
    - main

trigger: none

pool: gfx1100

steps:
# download tasks has built in 4x retry download count
# these will download last passing build for that branch
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: ROCmPOCm
    pipeline: llvm-project
    specificBuildWithTriggering: true
    branchName: amd-staging
    extractTars: true
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: ROCmPOCm
    pipeline: ROCT-Thunk-Interface
    specificBuildWithTriggering: true
    branchName: master
    extractTars: true
- script: 'ls -1R $(System.ArtifactsDirectory)'
  displayName: 'Artifact listing'