resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: github.com_amd-jmacaran
    name: amd-jmacaran/pipelines
  - repository: release_repo
    type: github
    endpoint: github.com_amd-jmacaran
    name: amd-jmacaran/roctracer
    ref: refs/tags/rocm-6.1.0

variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

trigger: none

jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/roctracer.yml@pipelines_repo
    parameters:
      checkoutRepo: release_repo
