parameters:
- name: checkoutRepo
  type: string
  default: 'self'
- name: aptPackages
  type: string
  default: 'cmake ninja-build git'

jobs:
- job: composable_kernel
  variables:
  - group: common
  - template: /.azuredevops/variables-global.yml
  pool: 'Alex Test'
  container:
    image: rocm/dev-ubuntu-22.04:6.1
  workspace:
    clean: all
  steps:
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/preamble.yml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
    parameters:
      checkoutRepo: ${{ parameters.checkoutRepo }}
  - ${{ if parameters.aptPackages }}:
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies.yml
      parameters:
        aptPackages: ${{ parameters.aptPackages }}
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
    parameters:
      extraBuildFlags: >-
        -DCMAKE_CXX_COMPILER=hipcc
        -DCMAKE_BUILD_TYPE=Release
        -DBUILD_CLIENTS=ON
        -L
        -GNinja
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml
