jobs:
- job: rocm_smi_lib
  timeoutInMinutes: 120
  variables:
  - group: common
  - template: /.azuredevops/variables-global.yml
  pool: ${{ variables.HIGH_END_BUILD_POOL }}
  workspace:
    clean: all
  steps:
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/preamble.yml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
# ${{ }} are resolved during compile-time
# so this next step is skipped completely until
# we define explicit aptPackages needed to install
  - ${{ if parameters.aptPackages }}:
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies.yml
      parameters:
        aptPackages: ${{ parameters.aptPackages }}
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
    parameters:        
      extraBuildFlags: >-
        -GNinja
        -DCMAKE_CXX_COMPILER=hipcc
        -DCMAKE_BUILD_TYPE=Release
        -DROCM_PATH=/opt/rocm
        -DCMAKE_PREFIX_PATH=/opt/rocm
        -DBUILD_TEST=ON
        -DAMDGPU_TARGETS="gfx1100;gfx1101;gfx1102"
        -DAMDGPU_TESTTARGETS="gfx1100;gfx1101;gfx1102"
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/test.yml
    parameters:
      testDir: tests/rocm_smi_test
      testExecutable: ./rsmitst
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml
