parameters:
- name: checkoutRepo
  type: string
  default: 'self'
- name: aptPackages
  type: string
  default: 'cmake libgtest-dev libdw-dev libsystemd-dev libelf-dev libnuma-dev libpciaccess-dev'
- name: pipModules
  type: string
  default: 'pyyaml==5.3.1 Cppheaderparser websockets matplotlib lxml barectf pandas'

jobs:
- job: rocprofiler
  variables:
  - group: common
  - template: /.azuredevops/variables-global.yml
  pool:
    vmImage: ${{ variables.LOW_END_BUILD_POOL }}
  container:
    image: rocm/dev-ubuntu-22.04:6.1
  workspace:
    clean: all
  steps:
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/preamble.yml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
    parameters:
      checkoutRepo: ${{ parameters.checkoutRepo }}
  - ${{ if parameters.aptPackages }}:
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies.yml
      parameters:
        aptPackages: ${{ parameters.aptPackages }}
        pipModules: ${{ parameters.pipModules }}
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-download.yml
    parameters:
      componentName: llvm-project
      branchName: amd-staging
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
    parameters:
      extraBuildFlags: >-
        -DCMAKE_MODULE_PATH="$(Build.SourcesDirectory)/cmake_modules;$(Agent.BuildDirectory)/rocm/lib/cmake"
        -DCMAKE_PREFIX_PATH="$(Agent.BuildDirectory)/rocm"
        -DUSE_PROF_API=1
        -DGPU_TARGETS="gfx1100"
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml
