parameters:
- name: checkoutRepo
  type: string
  default: 'self'
- name: checkoutRef
  type: string
  default: ''
- name: aptPackages
  type: string
  default: 'cmake ninja-build rocrand hiprand rocfft libboost-program-options-dev googletest libfftw3-dev'

jobs:
- job: rocTHRUST
  variables:
  - group: common
  - template: /.azuredevops/variables-global.yml
  pool:
    vmImage: ${{ variables.LOW_END_BUILD_POOL }}
  container:
    image: ${{ variables.DOCKER_IMAGE_NAME }}:${{ variables.LATEST_DOCKER_VERSION }}
  workspace:
    clean: all
  steps:
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies.yml
    parameters:
      aptPackages: ${{ parameters.aptPackages }}
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/preamble.yml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
    parameters:
      checkoutRepo: ${{ parameters.checkoutRepo }}
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
    parameters:
      extraBuildFlags: >-
        -GNinja
        -DCMAKE_CXX_COMPILER=hipcc
        -DCMAKE_BUILD_TYPE=Release
        -DROCM_PATH=/opt/rocm
        -DCMAKE_PREFIX_PATH=/opt/rocm
        -DCPACK_SET_DESTDIR=OFF
        -DCPACK_INCLUDE_TOPLEVEL_DIRECTORY=OFF
        -DBUILD_TEST=ON
        -DBUILD_BENCHMARK=ON
        -DBUILD_EXAMPLE=ON
        -DAMDGPU_TARGETS="gfx1100;gfx1101;gfx1102"
        -DAMDGPU_TESTTARGETS="gfx1100;gfx1101;gfx1102"
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml

