# ==== copy this ====
parameters:
- name: checkoutRepo
  type: string
  default: 'self'
- name: aptPackages
  type: string
  default: 'cmake ninja-build libgtest-dev git'
# ========
jobs:
- job: rocWMMA
  timeoutInMinutes: 180
  variables:
  - group: common
  - template: /.azuredevops/variables-global.yml
  # ==== copy this ====
  pool:
    vmImage: ${{ variables.LOW_END_BUILD_POOL }}
  container:
    image: rocm/dev-ubuntu-22.04:6.1
  workspace:
    clean: all
  # ========
  steps:
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/preamble.yml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
   # ==== copy this ====
    parameters:
      checkoutRepo: ${{ parameters.checkoutRepo }}
   # ========
  - ${{ if parameters.aptPackages }}:
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies.yml
      parameters:
        aptPackages: ${{ parameters.aptPackages }}
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
    parameters:
      extraBuildFlags: >-
        -DCMAKE_CXX_COMPILER=hipcc
        -DCMAKE_BUILD_TYPE=Release
        -DROCM_PATH=/opt/rocm
        -DCMAKE_PREFIX_PATH=/opt/rocm
        -DAMDGPU_TARGETS=gfx1100
        -DROCWMMA_BUILD_VALIDATION_TESTS=ON
        -DROCWMMA_BUILD_BENCHMARK_TESTS=OFF
        -DROCWMMA_BUILD_SAMPLES=OFF
        -GNinja
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/test.yml
    parameters:
      testDir: build
      testExecutable: ctest
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml
